### ISSUE TITLE
Build ETA and EMA on macOS

### ISSUE THREAD

**Issue by rdmitr** [Refinitiv/Elektron-SDK#101]
I tried building ETA and EMA on macOS, and succeeded with only a handful of minor tweaks to the build system and the source code, which are not expected to affect the Linux and Windows builds.

The changes are available in the "build-macos" branch in my fork of the Elektron repo.

Would you consider merging these into the upstream?

**Comment by rdmitr** [comment]
Specifically, this commit contains the required changes: https://github.com/rdmitr/Elektron-SDK/commit/e1c4d77017acc0f72f13e4eeb71f465c1125349c

**Comment by brettjbush** [comment]
@rdmitr - thank you for providing these changes for macOS support, as well as the additional pull requests you have provided.

Regarding your recent code contributions, if you are interested in becoming a verified Contributer to Refinitiv/Elektron-SDK (having your username and commits preserved in the git commit history), please read, sign, and submit one of the following forms described in the Contributing portion of the Refintiv/Elektron-SDK README.md, depending on if you are an Individual or represent an Entity.
https://github.com/Refinitiv/Elektron-SDK#contributing

Regarding macOS support of ESDK, please submit the branch linked above as a Pull Request for our team to review.

**Comment by rdmitr** [comment]
@brettjbush Thanks! We will submit the form soon, and I'll prepare a pull request.
