### ISSUE TITLE
UPA Java 7.6 unexpected return codes from Channel.read: 1448, 2896

### ISSUE THREAD

**Issue by zfarberov** [Refinitiv/Elektron-SDK#102]
Hello @Elektron-SDK,

Pleas help identify unexpected return codes from Channel.read: 1448, 2896

Re:
https://community.developers.thomsonreuters.com/questions/41497/java-upa-api-channelread-returning-1448-error-code.html

Looking for meaning, recommended processing.

Thanks much,
-Zoya

**Comment by zfarberov** [comment]
Java

**Comment by brettjbush** [comment]
@zfarberov thank you for reaching out with your question.

A return code that is > 0 indicates that the Channel.read call was successful
and there are remaining bytes in the input buffer to be read again.

I noticed that you also received a recent response on the Developer Community as well which may have satisfied your question. If so, feel free to close this GitHub Issue at your convenience. However, if you have further questions feel free to ask as well.
