### ISSUE TITLE
Valgrind is showing memory errors in the C++ EMA API and its causing crash for the application

### ISSUE THREAD

**Issue by pawan-jha** [Refinitiv/Elektron-SDK#103]
I Have written a application using C++ EMA API, the application is written to capture the market data using EMA API. 
The application is crashing for same set of rics for 24 hour capture process (the crash is not happening frequently , if i run the application 3 to 4 times then once its crashing) . 
I have complied/Linked my application with both EMA 1.2.1 and EMA 1.3.0 version but i am facing the same issue with both the EMA versions.

**When i started the application with valgrind then Both the version of EMA (EMA 1.2.1 and EMA 1.3.0) is showing Invalid read error.( I have compiled/linked the application with both EMA version and created 2 different binary)** 
I am suspecting that my application is crashing because of EMA API's invalid read issue.

**Please Find the attached valgrind report and  the core file generated by application.**

[core.zip](https://github.com/Refinitiv/Elektron-SDK/files/3102991/core.zip)
[Valgrind_With_EMA1.2.1.log](https://github.com/Refinitiv/Elektron-SDK/files/3102944/Valgrind_With_EMA1.2.1.log)
[Valgrind_With_EMA1.3.0.log](https://github.com/Refinitiv/Elektron-SDK/files/3102945/Valgrind_With_EMA1.3.0.log)

**Comment by brettjbush** [comment]
@pawan-jha thank you for your feedback. Our team is reviewing your report. 

What operating system and version are you experiencing this issue on?

**Comment by pawan-jha** [comment]
Hi @brettjbush 
I have compiled/linked(statically linked) the application on below server.
**uname -a ==> Linux rhel6-build 2.6.32-696.el6.x86_64 #1 SMP Tue Feb 21 00:53:17 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
Machine OS : GNU/Linux , Processor : x86_64
Description:    Red Hat Enterprise Linux Server release 6.9 (Santiago)
Version : 6.9**

And i am running the application on below 3 server and on all the 3 server application is crashing as i mentioned above and its showing memory error(Invalid read) in the EMI API  when i started the application with Valgrind(on all the 3 servers).

**Server1:**
uname -a ==> Linux rhel6-build 2.6.32-696.el6.x86_64 #1 SMP Tue Feb 21 00:53:17 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
Machine OS          :       GNU/Linux , Processor : x86_64
Description           :       Red Hat Enterprise Linux Server release 6.9 (Santiago)
Version                 :        6.9

**Server2:**
uname -a ==> Linux sg1d-ddnctdb01a 2.6.32-431.5.1.el6.x86_64 #1 SMP Tue Feb 11 11:09:04 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
Machine OS :     GNU/Linux , Processor : x86_64
Description:       Red Hat Enterprise Linux Server release 6.5 (Santiago)
Version :            6.5

**Server3:**
uname -a  ==> Linux dt1d-ddnctdb01a 2.6.32-431.5.1.el6.x86_64 #1 SMP Tue Feb 11 11:09:04 PST 2014 x86_64 x86_64 x86_64 GNU/Linux 
Machine OS   :       GNU/Linux , Processor : x86_64
Description    :       Oracle Linux Server release 6.5
Version          :        6.5

**Comment by brettjbush** [comment]
@pawan-jha thank you for providing this information. 

Could you also provide call stack of this issue?

If you are an RDC member, please raise this issue through our Support channel to receive more rapid feedback.

**Comment by pawan-jha** [comment]
Hi @brettjbush 
Find the attached call stack of the crash. 
**This application is compiled/linked with EMA1.3.0 Debug  version so that we can get more information.
[CallStack.txt](https://github.com/Refinitiv/Elektron-SDK/files/3106005/CallStack.txt)
**
With the EMA1.3.0 Optimized version also call stack was same(with less info).

**Comment by soranat** [comment]
@pawan-jha  This issue was fixed in Elektron-SDK version 1.3.1.G2.

Please let us know if fix addresses the issue you've reported. Closing for now - please re-open as needed.

**Comment by pawan-jha** [comment]
hi @soranat Thanks for the update.
Can you please tell me from where i can download this updated(fixed) EMA Library.
I need complied version of EMA library which i can use(link) directly with my application as i have used earlier to build my application.

**Comment by xipherix** [comment]
@pawan-jha 
The fixed in ESDK 1.3.1.G2 is now added to the latest official release of ESDK 1.4.0. You can change the tags in the ESDK master branch to 1.4.0.L1 or download the package from
https://developers.refinitiv.com/elektron/elektron-sdk-cc/downloads

**Comment by pawan-jha** [comment]
hi @xipherix  @brettjbush @soranat 
I am using EMA API to capture LevelII data. Can you please me how i can know from EMA API that primary summary message is competed ? As you know For LevelII primary summary is followed by many  initial order book. How can i know this is the last message (order) from the inital order book ?  Is EMA API provide any way to know this ?

**Comment by soranat** [comment]
When you subscribe to a Message By Order (MBP) or Message By Price (MBO) RIC, the initial refresh may arrive in multiple parts.  Each message part will have a part number and the final message will have to “REFRESH COMPLETE” flag on it which the RefreshMsg::getComplete() method returns **true** if the message is the last part of the multi-part refresh messages.  Please note that you may receive updates before the initial refresh is complete – these must be handled by your application.

**Comment by pawan-jha** [comment]
Hi @soranat  **Thanks a lot for the information.** 
So when RefreshMsg::getComplete() method returns **true(1)**  for the particular RIC that is the last part the refresh message. Is all part of the refresh message comes as part for Summary Data ?   Also, what is use of **map::getTotalCountHint()** ? 
Will map::getTotalCountHint() will help in any case ?

**Comment by umernalla** [comment]
Hi @pawan-jha 
Yes - the final part of a multi-part refresh message will return getComplete() as true
getTotalCountHint() just provides an approximation of how many entries to expect - i.e. a Hint - to help you optimise caching at the application level.
The actual number of orders you receive can differ since you are dealing with live data and the number of orders could have changed in real-time between when the server sends you the initial response and the final part.
With regards PartNum - the RDM_UsageGuide describes this as an optional value - when it is used it would specify the part number of a multi-part refresh.

**Comment by pawan-jha** [comment]
Hi @umernalla Thanks for the info.

Does EMA provide any way retrieve only  **market status information** without subscribing any RIC ?

**Comment by umernalla** [comment]
Hi @pawan-jha - 
Please expand on what you mean by Market Status information? 
There is a way of discovering the health of our realtime delivery systems - but I suspect this is not what you are after https://developers.refinitiv.com/en/article-catalog/article/how-discover-health-elektron-real-time-infrastructure-using-ema-java-api

**Comment by pawan-jha** [comment]
Hi @umernalla  Thanks for the info.
I want to know market status for the exchange (like currently market(exchange) is in which state  **"close/open/halt/or any other"** ) without subscribing any RIC by using EMA API ?

**Comment by umernalla** [comment]
EMA request messages require an item name / RIC code in order to submit a Request Message.
I recommend you contact our Content Helpdesk to see if they are aware of any RICs codes that provide the kind of status information you are after on an exchange by exchange basis. You can create a Content  query for Refinitiv Real-Time at https://my.refinitiv.com/content/mytr/en/productsupport.html
I recommend you don't mention EMA - in case the query gets wrongly redirected to API support.

**Comment by pawan-jha** [comment]
@umernalla  Thank a lot for the info.

**Comment by pawan-jha** [comment]
I am creating a c++ application using EMA API. While compiling i am getting below error 
_**/usr/bin/ld: i386:x86-64 architecture of input file `../lib/rhel7.i386.gcc9/libEMA.a(ElementList.cpp.o)' is incompatible with i386 output**_
Can anyone suggest me how to fix this problem ?

**Comment by pawan-jha** [comment]
hi @xipherix  @umernalla  @brettjbush  @soranat 
**_I am a Rifinitiv Internal Employee (Pawan.Kumar@Refinitiv.com)._** 
_I am developing a application which needs **_32-bit c++ Elektron SDK  (EMA API)_** .  Can you please tell me from where i can download 32-bit EMA API (ESDK) package ?_ 

Also when i trying to access https://developers.refinitiv.com/elektron/elektron-sdk-cc/downloads i am not able to login to this page. Whom i need to contact to get the access related to ESDK package?

**Comment by pawan-jha** [comment]
hi @xipherix  @umernalla  @brettjbush  @soranat @seba5  @aclouras @vlevendel @MitchellKato
I have downloaded ESDK package 1.5.0 package and  _I am trying to build ESDK package for 32-bit support_. 
Command used to build ESDK  :   _**cmake -Hesdk -Bbuild-esdk -DBUILD_32_BIT_ETA=ON**_
Build Server : **_GNU/Linux x86_64  3.10.0-1127.el7.x86_64_**  

Build is not getting completed successfully. I am getting below error 

[100%] Completed 'cjson'
[100%] Built target cjson
Prebuilt libraries not found: librssl_LIBRARY_OPTIMIZED-NOTFOUND, in
        /home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: librssl_shared_LIBRARY_OPTIMIZED-NOTFOUND, in
        /home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: librsslJsonConverter_shared_LIBRARY_OPTIMIZED-NOTFOUND, in
        /home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: librsslVA_LIBRARY_OPTIMIZED-NOTFOUND, in
        /home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: librsslVA_shared_LIBRARY_OPTIMIZED-NOTFOUND, in
        /home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: libansi_LIBRARY_OPTIMIZED-NOTFOUND, in
        /home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
-- Skipping Eta Doxygen Build: BUILD_ETA_DOXYGEN:OFF
-- Skipping Ema Library Build: BUILD_EMA_LIBRARY:OFF
-- Configuring incomplete, errors occurred!
 
**_### Can you please tell me how to  get rid of this error and take 32-bit successful build for ESDK ?_**

**Comment by vlevendel** [comment]
> hi @xipherix @umernalla @brettjbush @soranat
> **_I am a Rifinitiv Internal Employee ([Pawan.Kumar@Refinitiv.com](mailto:Pawan.Kumar@Refinitiv.com))._**
> _I am developing a application which needs **_32-bit c++ Elektron SDK (EMA API)_** . Can you please tell me from where i can download 32-bit EMA API (ESDK) package ?_
> 
> Also when i trying to access https://developers.refinitiv.com/elektron/elektron-sdk-cc/downloads i am not able to login to this page. Whom i need to contact to get the access related to ESDK package?

https://developers.refinitiv.com/en/api-catalog/elektron/elektron-sdk-cc  is the new location for RTSDK (ESDK has been renamed to RTSDK) packages.  Searching for "ESDK" on the Developer Community and clicking on "API"s will lead to the same page.

We do not ship 32 lib libraries but do provide a way to build your ETA own using cmake.  This is not supported for EMA.

**Comment by pawan-jha** [comment]
Hi @vlevendel 
Thanks for the Info.
 
**_So we cant build EMA for 32 bit using cmake ??_**

**Comment by MitchellKato** [comment]
As stated both here and in https://github.com/Refinitiv/Real-Time-SDK/issues/166, EMA is not supported as a 32-bit library.

**Comment by pawan-jha** [comment]
@xipherix @umernalla @brettjbush @soranat @MitchellKato 
Hi 
I have written a application using EMA API which is subscribing data from TREP. I am subscribing  same ric in both **dynamic and static mode**  ,  When i am receiving the response  then how to know which response is for static and which response is for dynamic ? **Is there anyway to find the mode of subscription from response message ?**

**Comment by pawan-jha** [comment]
This was related to “streaming” versus “snapshot. An enumeration representing item stream state gives the information regarding this.
**OpenEnum -->**  Indicates   the stream is opened and will incur interest after the final refresh.
**NonStreamingEnum  -->**  Indicates   the item will not incur interest after the final refresh.
