### ISSUE TITLE
Please restore version headers, eg EmaVersion.h

### ISSUE THREAD

**Issue by DuncanSands** [Refinitiv/Elektron-SDK#105]
In the 1.3.0.L1 ESDK C++/C Release, the following files were removed:
  ./Ema/Src/Access/EmaVersion.h
  ./Eta/Include/rsslVersion.h
  ./Eta/Include/rsslVersion.h
Can you please put them back.  We're not using cmake, which makes it annoying to have to run cmake to generate these.

**Comment by vlevendel** [comment]
@DuncanSands are using GitHub directly or getting the package?

**Comment by DuncanSands** [comment]
The package, Elektron-SDK-1.3.0.L1.linux_0.zip.

**Comment by vlevendel** [comment]
@DuncanSands ESDK1.3.1.L1 adds these files back in.  Closing issue.  Please reopen if there are more concerns. Thank you.
