### ISSUE TITLE
Building C++ Elektron SDK on our Linux platform

### ISSUE THREAD

**Issue by envtkach19** [Refinitiv/Elektron-SDK#107]
Our case is most similar to https://github.com/Refinitiv/Elektron-SDK/issues/86 but there does not seem to be any final resolution there. The issue is that prebuilt libraries seem to come only in two flavors, as above issue name suggests "C++ SDK dependency: builds for non RHEL6_64_GCC444 or OL7_64_GCC482"

We initially attempted approach similar to above forum issue by creating symlinks so named ( LIN3_64_GCC485 ) pointing to RHEL6_64_GCC444 under a few places where cmake / build stumbled, like installdb ; Cpp-C/Eta/Libs and Cpp-C/Ema/Libs.

Having to create symlinks does not sound like a great solution but it got us over this initial hurdle and then we encountered below error related to Dacs;

[ 27%] Built target Provider_shared make[2]: *** No rule to make target `Elektron-SDK-BinaryPack_dacs_LIBRARY-NOTFOUND', needed by `/home/auser/Elektron-SDK-1.3.0.L1.linux/setup/Elektron-SDK-1.3.0.L1.linux.rrg/Cpp-C/Eta/Executables/LIN3_64_GCC485/Optimized/authlock'.
Stop. make[1]: *** [Cpp-C/Eta/Applications/Examples/AuthLock/CMakeFiles/authlock.dir/all] Error 2

The root cause seems to be that for dacs and ansi Utils libraries cmake step computed target names that are LIBRARY-NOTFOUND.

So this is where my colleague and I stopped for now; I am reluctant to start changing cmake files for now as I feel this should just work.

If I examine CMakeCache.txt, for example, we see that include path for ansi and dacs looks good but for some reason library path is not computed correctly by cmake even though it exists as Libs/RHEL6_64_GCC444/Optimized/libdacs.a and we created symlink based Libs/LIN3_64_GCC485/Optimized/libdacs.a

What is the right way to approach both issues: (1) initial issue -- building on Linux/gcc but different from anticipated build targets and (2) specifics dacs Cmake LIBRARY_NOT_FOUND issue

Any suggestions?

**Comment by geoffmallard** [comment]
Yes, internally we only support pre-built libraries for a few Linux versions and flavors.  However, the CMake build does attempt to normalize those dependencies to help with linking the pre-built libraries on other Linux platforms.  The path created by the CMake build which contains, LIN3_64_GCC485, gives a hint you may not have lsb_release installed or in your path.  If lsb_release is not found, then it will attempt to use 'uname' to identify the OS.  The results from uname are best guess and as we identify new cases, it will be updated.  Can you tell me on what Linux are you try to build?

**Comment by envtkach19** [comment]
Hi,

Our Linux is 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

We have a number of flavors including some older ones; I am attempting it on this one for now as I expect bigger problems on the older ones, so trying on this one.

I can try to get lsb_release installed if that helps.

**Comment by geoffmallard** [comment]
Yes, that would be great if you could verify if building with lsb_release installed still produces this problem.  The OS on my VirtualBox is the same as your machine.  I was able to verify my build, using gcc v4.8.5, links with the dacs library:  Elektron-SDK-BinaryPack/Cpp-C/Eta/Utils/Dacs/Libs/OL7_64_GCC482/Optimized/libdacs.a
Let me know if you have different results.

**Comment by envtkach19** [comment]
Hi,
Thanks, I did a build from scratch and it looks like it works.
I will now try to understand how to use the SDK for our purpose.
