### ISSUE TITLE
ESDK 1.3 EMA J - cannot specify Location for Session Management with Programmatic Config?

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Elektron-SDK#109]
I modified EMA consumer example 113 to use Programmatic Config (ESDK 1.3)
If I use the following I can connect:
```
innerElementList.add(EmaFactory.createElementEntry().ascii("ChannelType", "ChannelType::RSSL_ENCRYPTED"));
innerElementList.add(EmaFactory.createElementEntry().ascii("Host", "amer-3.pricing.streaming.edp.thomsonreuters.com"));
innerElementList.add(EmaFactory.createElementEntry().ascii("Port", "14002"));
innerElementList.add(EmaFactory.createElementEntry().intValue("EnableSessionManagement", 1));
```
But if I try the following:
```
innerElementList.add(EmaFactory.createElementEntry().ascii("ChannelType", "ChannelType::RSSL_ENCRYPTED"));
innerElementList.add(EmaFactory.createElementEntry().ascii("Location", "us-east"));
innerElementList.add(EmaFactory.createElementEntry().intValue("EnableSessionManagement", 1));
```
I get:
ClientName: ChannelCallbackClient
    Severity: Warning
    Text:    Received ChannelDownReconnecting event on channel Channel_1
        RsslReactor @4b0d79fc
        RsslChannel @4c1909a3
        Error Id 0
        Internal sysError 0
        Error Location Reactor.processWorkerEvent
        Error text Error initializing channel: errorId=-1 text=Connection refused: no further information
Also tried not setting a Location to see if uses the default - but still get the same error.

**Comment by brettjbush** [comment]
@umernalla - thank you, our team is currently investigating the issue you have raised. What OS is the Consumer113 example running on?

**Comment by umernalla** [comment]
Windows 10, java version "1.8.0_102"
FYI: When using the unmodified version of consumer113 with default EMAConfig.xml (i.e. Channel_4 Location value 'us-east') - it also works fine.
Just seems to be when using Programmatic config...
