### ISSUE TITLE
Provider fails to accept client logins with dispatch timeOut = NoWaitEnum

### ISSUE THREAD

**Issue by sergey-at-ark** [Refinitiv/Elektron-SDK#110]
To serve market data over our company network we start EMA Interactive OmmProvider with OperationalModel set to UserDispatchEnum. When OmmProvider::dispatch() is called with its default timeOut = NoWaitEnum, clients cannot login to the server.

Specification for OmmProvider::dispatch:https://docs-developers.refinitiv.com/1564020531520/4725/Docs/refman/ema/a00059.html#aacc00f0651fc18fe95e5c90bfbe1e31d

How to reproduce the bug:1. Use 130_MarketPrice_UserDispatch example as a serverhttps://github.com/Refinitiv/Elektron-SDK/blob/master/Cpp-C/Ema/Examples/Training/IProvider/100_Series/130__MarketPrice__UserDispatch/IProvider.cpp

2. Remove timeouts from dispatch() calls, i.e:7576		while ( itemHandle == 0 ) provider.dispatch( 1000 ); // change to provider.dispatch()77

3. Use 130_MarketPrice_UserDisp example as a client:https://github.com/Refinitiv/Elektron-SDK/tree/master/Cpp-C/Ema/Examples/Training/Consumer/100_Series/130__MarketPrice__UserDisp

Application background:
  We have hybrid application without threads that serves market data to algorithms running on the same machine and other machines (clients). The main server loop:
  while (is_running()) { 
  omm_consumer_->dispatch(0);
  omm_provider_->dispatch(1000); // This will be changed to 29 microseconds till bug is investigated.
 }
Impact: Long delay in the hybrid application loop between the time market data arrived and the time market data delivered to processing algorithms.

**Comment by brettjbush** [comment]
@sergey-at-ark thank you for submitting your issue. Our team is currently investigating. What OS are you experiencing this behavior on?

**Comment by sergey-at-ark** [comment]
Hi Brett,

Ubuntu 18 and CentOS 6.
Did you manage to reproduce the issue?

Thanks
Sergey

**Comment by tmurthy** [comment]
Hi Sergey,

I have been able to reproduce the issue you reported. Our development team is currently looking into it.

Please let me know if you can take the fix in a  GitHub push

Regards
- Tina

**Comment by sergey-at-ark** [comment]
Fantastic,
I can take the fix in any shape or form.
Thanks
Sergey

**Comment by sergey-at-ark** [comment]
Hello,
Is there any progress in the last two weeks on that issue?
Regards
Sergey

**Comment by tmurthy** [comment]
The Jira is currently in development backlog. I have forwarded your request to development, will update you as soon as I get something.

Thanks

**Comment by sergey-at-ark** [comment]
Hi thurthy,

What does this mean "in development backlog"? Have you started working on
it?

Thanks
Sergey

**Comment by sergey-at-ark** [comment]
Tina,
Could you provide a patch or at least let me know what causing the problem?
Thank you
Sergey

**Comment by vlevendel** [comment]
@sergey-at-ark Please let us know if fix addresses the issue you've reported. Closing for now - please re-open as needed.

**Comment by sergey-at-ark** [comment]
Yes, I will as soon as I can test our new server without patches.
Thanks
Sergey

**Comment by sergey-at-ark** [comment]
Yes, the bug is fixed in the latest GitHub SDK and all our C++ tests
passed. I can't vote for Java.
We will be useding new SDK in production starting from tomorrow.
Thank you very much.
Sergey Derevyanko
Ark International Group

**Comment by sergey-at-ark** [comment]
Yes, the bug is fixed in the latest GitHub SDK and all our C++ tests passed. I can't vote for Java.
We will be using new SDK in production starting from tomorrow.
Thank you very much.
