### ISSUE TITLE
Add port info OmmConsumerEvent::getChannelInformation

### ISSUE THREAD

**Issue by RegardsIM** [Refinitiv/Elektron-SDK#113]
I use C++ SDK
I override AppClient::onStatusMsg and call OmmConsumerEvent::getChannelInformation to extract information about the channel
I may take a host from it but I can't take a port
As I was advised on [EMA portal](https://community.developers.refinitiv.com/questions/46970/the-relationship-between-consumer-channels-and-con.html) it's not possible to know what port was used by channel for connection and it's better to create an issue here

**Comment by vlevendel** [comment]
@RegardsIM We will consider this enhancement request for a future release. Thank you for making this request.
