### ISSUE TITLE
Upgrade httpcomponents-core dependency

### ISSUE THREAD

**Issue by cowwoc** [Refinitiv/Elektron-SDK#114]
Please upgrade httpcomponents from version 4.4.10 to 4.4.11 to fix this bug: https://github.com/apache/httpcomponents-core/pull/93

**Comment by MitchellKato** [comment]
Thanks for bringing this up to our attention.  We'll make sure it's fixed in a future release.

**Comment by vlevendel** [comment]
@cowwoc This issue has been addressed with ESDK1.4.0.L1.  Please reopen if you find otherwise.  Thank you.
