### ISSUE TITLE
Support for Posting on EMA Provider

### ISSUE THREAD

**Issue by pparlapiano** [Refinitiv/Elektron-SDK#117]
The EMA C++ api does not have full support for implementing an EMA provider able to react to post requests. The onPostMsg(...) handler is never notified by EMA.
Please fill the gap.

Thanks
Paolo

**Comment by vlevendel** [comment]
@pparlapiano Thank you for noting the gap. We do have an internally tracked issue for this already.

**Comment by miczuc** [comment]
Hi. Yes, I noticed this also. This contradicts the documentation in my opinion.
The callback method is never called and you wonder, what happens.
You don't get a hint unless you have set the logging level to 'Verbose' ....

**Comment by lars-zimmer** [comment]
Hello,
there is news on this issue.
We would like to integrate the EMA in our product. But for that the fehelr would have to be fixed.
So I would be very thankful to get a fix date

**Comment by vlevendel** [comment]
@pparlapiano This is addressed with 1.5.0.G1.  Closing.
