### ISSUE TITLE
Inconsistency contents in default and description of ReissueTokenAttemptInterval and ReissueTokenAttemptLimit parameter

### ISSUE THREAD

**Issue by Pimchaya** [Refinitiv/Elektron-SDK#120]
In "Table 3: Consumer Group Parameters (Continued)" page 9 of EMAJ_ConfigGuide.pdf shipped with 1.3.1.G1 package, the default of ReissueTokenAttemptInterval is -1 but the description mentions 5000.   The default of ReissueTokenAttemptLimit is 5000 but the description mentions -1. Should the document be fixed?

**Comment by vlevendel** [comment]
@Pimchaya This is fixed in the documentation with ESDK 1.4.0.L1.
