### ISSUE TITLE
[Enhancement] Value Add Watchlist and Closed_Recover status message

### ISSUE THREAD

**Issue by ariestae** [Refinitiv/Elektron-SDK#122]
VA Watchlist consumer will flood the channel with requests if the provider replied with Closed_Recover status.  
It seems that VA Watchlist does not wait before sending a new request.

![Watchlist_Closed_recover](https://user-images.githubusercontent.com/14887336/67471946-7e7bdb00-f67a-11e9-80b5-c0f35d387a5d.png)

The watchlist should wait after receiving a Closed_Recover status and there should be another parameter in `RsslConsumerWatchlistOptions` that let us specify the timeout.

**Comment by MitchellKato** [comment]
First off, which version of ESDK are you using?  In addition, which platform are you seeing this behavior on?

In addition, how long is the requestTimetout set in the watchlistOptions?

Can you please share a code snippet for the consumer?  I am unable to reproduce this behavior.  I'm getting a timeout from the watchlist when a state of CLOSED_RECOVER and a data state of SUSPECT is sent.  

Thanks,
Mitchell

**Comment by MitchellKato** [comment]
No response after months, closing this issue.
