### ISSUE TITLE
ETA 3.4.0 Ansi Page example fails.

### ISSUE THREAD

**Issue by zinc1oxide** [Refinitiv/Elektron-SDK#124]
We have a client using ANSI Pages with ETA on Windows.  See [this question](https://community.developers.refinitiv.com/questions/51994/elektron-sdk-140-window-compile-and-link-issues.html?childToView=52836#comment-52836).  

According to the client, they have an existing application that links fine using ETA 3.1.0 however, complains with this error when using ETA 3.4.0: 

> error LNK2019: unresolved external symbol toascii referenced in function _ansi_pch

Within the documentation, there is a [Package Directory Change](https://docs-developers.refinitiv.com/1575926931038/16304/Docs/WebDocs/wwhelp/wwhimpl/js/html/wwhelp.htm#href=Installation_Guide/ESDK_C_Installation_Guide.1.04.html)s page which says:

> DACS and ANSI libraries have been moved to directory Elektron-SDK-BinaryPack/Cpp-C/Eta/Utils.

However, I don't see any ANSI libraries, just DACS

![image](https://user-images.githubusercontent.com/5118980/70475227-240bd200-1aa2-11ea-923f-218fe668d679.png)

Normally I would determine the proper libs by building an example ESDK application but there doesn't appear to be any to verify.  Can anyone confirm or verify the list of libs required and the proper solution.
thanks.

**Comment by vlevendel** [comment]
@zinc1oxide Thank you for bringing this to our notice. ANSI has been open sourced in version 3.3.0.L1. We'll check why the build is failing and address in a future github push.

**Comment by IProkopenkoRef** [comment]
Fixed in 1.4.0.G1
