### ISSUE TITLE
ETA-windows openssl with tlsv1.2, connect for a while will fail

### ISSUE THREAD

**Issue by samigitlab** [Refinitiv/Elektron-SDK#125]
![csr](https://user-images.githubusercontent.com/33648540/71227639-df422f80-231a-11ea-9505-1972fe4ab378.png)

**Comment by vlevendel** [comment]
@samigitlab Which version of ESDK are you using? Is this a consumer or provider application? How long is connection up before you see this failure? Is that consistent? Do you get data successfully after connection up before failure? Is this issue reproducible with an example application?

**Comment by samigitlab** [comment]
@vlevendel  I use Quantum Framework Dependencies_v1.3.11, i think both ESDK1.3.1.L1 and 1.4.0.L1 have the same problem. It's a provider application, it happens at random time around 1 minute, and consistent happen every time. When it's up ,can get data successfully , but will fail soon. It can be reproduced.

**Comment by vlevendel** [comment]
@samigitlab Please attach sample code to reproduce the issue.

**Comment by vlevendel** [comment]
@samigitlab This may be address by a fix to another issue in version 1.5.0.G1 (recent push). Would you please try this version and let us know?  If it is still and issue, please re-open.
