### ISSUE TITLE
C++ ETA examples broken wrt RSSL_RET_WRITE_FLUSH_FAILED

### ISSUE THREAD

**Issue by steve-o** [Refinitiv/Elektron-SDK#127]
Per the documentation handling `RSSL_RET_WRITE_FLUSH_FAILED` should not call `rsslReleaseBuffer`, however all the examples do this.  The `rsslReactor` implementation however does not and correctly follows the _specification_ available.

https://github.com/Refinitiv/Elektron-SDK/blob/master/Cpp-C/Eta/Applications/Examples/Common/rsslSendMessage.c#L76

**Comment by MitchellKato** [comment]
None of the examples call rsslReleasebuffer after a RSSL_RET_WRITE_FLUSH_FAILED call.  In addition, this is properly handled in the Reactor, as the reactor will trigger an event to the worker thread to flush whenever the write FD is triggered.
