### ISSUE TITLE
EMA, 1.4 EmaConfig.xml <SysSendBufSize> is not set consistently on Linux, Ora7

### ISSUE THREAD

**Issue by zfarberov** [Refinitiv/Elektron-SDK#132]
Hello @Elektron-SDK development,

I  am observing that in ESDK 1.4, EMA, interactive provider,
<Server> -> <SysSendBufSize> is not reflected precisely on Linux.

(On Windows, the number that is is set in config is reflected by
event.getChannelInformation() 
system send buffer size printed.)

To reproduce,
I run IProv100 agains Cons100.

By default I see
system send buffer size: 131070

If in EmaConfig I set  under 5000, such as 1000, 
I see channel reporting 
system send buffer size: 4608

If I set over 5000, I see reported double, i.e.
<SysSendBufSize value="5000"/>
results in 10000, 
10000 
results in 20000
25000 results in 
system send buffer size: 50000

The issue was originally reported on developers forums:
https://community.developers.refinitiv.com/questions/55104/value-of-configuration-parameter-syssendbufsize-in.html

Please let me know what you think? 
Thanks,
-Zoya

**Comment by MitchellKato** [comment]
According to the socket(7) man page, Linux will double the value set with SO_SNDBUF and SO_RCVBUF on setsockopt().  This is an OS behavior.

http://man7.org/linux/man-pages/man7/socket.7.html

**Comment by zfarberov** [comment]
Hello @MitchellKato 
I see your point. and agree that this is part of the reason.
However, 
For smaller values (such as 1000) it does not appear to be the case, the setting is neither applied as is, nor applied doubled.  The resulting buffer is neither.
According to EMA Config Guide
"Specifies the size (in KB) of the system's send buffer for this channel.".
I.e. does not say that on Windows it specifies, but on Linux it's going to be consequently doubled?

**Comment by MitchellKato** [comment]
This is OS(and potentially OS configuration) specific, so it's not necessarily something that we're going to specifically document.

**Comment by zfarberov** [comment]
Thank you @MitchellKato,

I will convey your answer to developers portal as official.

**Comment by zfarberov** [comment]
Thank you @MitchellKato
