### ISSUE TITLE
ESDK C package README.md files refer to EDSK Java

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Elektron-SDK#133]
ESDK C 1.3 and 1.4 README.MD files state:

### Interoperability
ESDK **Java** supports connectivity to the following platforms:
- Enterprise Platform for Real-Time (RSSL/RWF connections) : ADS version 2.6 and higher, ADH version 2.6 and higher. 
- Elektron: Elektron Deployed, Elektron Hosted, Elektron Direct Feed

**Comment by vlevendel** [comment]
Thanks - typo will be fix in next release.
