### ISSUE TITLE
EMA C++: Provider configuration parameter SysSendBufSize is applied as number of bytes, not KB

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Elektron-SDK#137]
Hello.

I was wondering about the values shown in the toString() method of ChannelInformation, for
parameters  "system send buffer size" and "system receive buffer size".
I made a test and set parameter "\<SysSendBufSize\>" in the "\<Channel\>" section for my test provider.
I noticed, that the value is passed as number of bytes to the call setsockopt(.. SO_SNDBUF ..).
(On a Linux system you observe different values afterwards in the ChannelInformation,
because setsockopt(.. SO_SNDBUF ..) internally doubles the value and also clips it to a limited range, see man page.).
However, the configured value is obviously applied as number of bytes, and not kilo bytes, as stated in the configuration guide:
"Specifies the size (in KB) of the system's send buffer for this channel."

So there is a contradiction, Regards, Michael Zuck

**Comment by IProkopenkoRef** [comment]
Hi Michael
Thank you for noticing this inconsistency. This should read 'in Bytes'. Issue will be addressed in documentation

**Comment by vlevendel** [comment]
ConfigGuides have been updated.
