### ISSUE TITLE
ETA C++: Access Violation Closing Reactor Tunnel (over SSL)

### ISSUE THREAD

**Issue by varauder** [Refinitiv/Elektron-SDK#139]
My application has experienced intermittent connectivity issues when connecting to a TRCC hosted at thomsonreuters.com.
This usually handled gracefully and my app reconnects. This has been the case for many years.

On one occasion (which hasn't yet been repeated) the app crashed due to an Access Violation, dereferencing a null pointer.
The problem appears to be the handling of the ripcSSLSession::connection pointer.

Consider the following callstack:
>    ripcShutdownSSLSocket(void * session) Line 1671
>    rsslSocketChannelClose(RsslSocketChannel * rsslSocketChannel) Line 11493
>    ipcShutdownSockectChannel(RsslSocketChannel * rsslSocketChannel, RsslError * error) Line 11135
>    rsslSocketCloseChannel(rsslChannelImpl * rsslChnlImpl, RsslError * error) Line 8520
>    rsslCloseChannel(RsslChannel * chnl, RsslError * error) Line 1335
>    runReactorWorker(void * pArg) Line 567

ripcShutdownSSLSocket calls into SSL_set_shutdown (OpenSSL 1.1.1c) passing in the session->connection pointer, which is NULL.
OpenSSL performs no NULL checks resulting in an access violation.

Walking further up the callstack to rsslSocketChannelClose(), my core dump shows rsslSocketChannel->state is set to RSSL_CH_STATE_INITIALIZING.
Further, at this same stack frame rsslSocketChannel->intState is set to RIPC_INT_ST_CLIENT_TRANSPORT_INIT.
From the limited time I've spent looking at the ETA source code I'm wondering if, when the channel is initialising, there is an intermediate period where ripcSSLSession::connection has not yet been initialised (ie ripcSSLConnectInt has not yet been called).
If the connection is closed during this intermediate period, we get the above callstack resulting in an attempt to shutdown the SSL socket that hasn't yet been initialised.

Please could someone confirm if ETA should perform a NULL pointer check (or some other fix); or if I can somehow affect this behaviour in my application layer.

Windows Server 2012
MSVC 11 (VS2012)
eta3.3.1.L1.win.rrg 64-bit Static
OpenSSL 1.1.1.3

**Comment by MitchellKato** [comment]
Thank you for the detailed issue description!

I have a feeling that you're correct, that this is a race condition between the channel getting created, the OpenSSL session initialization, and the close.  We will investigate further, and I have raised a JIRA in the backlog.

Mitchell

**Comment by vlevendel** [comment]
@varauder Would you please re-test with latest version and let us know if this is addressed?

**Comment by varauder** [comment]
Looks good after testing with 1.5.0.G1
Thanks
