### ISSUE TITLE
RMTES Buffer apply not working consistently

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Elektron-SDK#74]
Hi,
I seem to have found an issue in EMA Java 1.2.0 with RMTES Buffer handling.

in example310__MarketPrice__Rmtes if I dump a field's rmtes() value before applying it to an existing RmtesBuffer, then it does not apply correctly to the existing  buffer...
e.g. the following does not work when you get an Update - the partial update overwrites the existing buffer content.
`if (fieldEntry.name().equals("ROW64_2"))
{
    System.out.println(fieldEntry.rmtes().toString());
    System.out.print("Fid: " + fieldEntry.fieldId() + " Name = " + fieldEntry.name() + " DataType: " + DataType.asString(fieldEntry.load().dataType()) + " Value: ");
	System.out.println((rmtesBuffer.apply(fieldEntry.rmtes())).toString());
}`

If I remove the first _System.out.println(fieldEntry.rmtes().toString())_ call then it works fine.
Obviously, not a big deal in the above context, but points to something not being right. I came across this because a developer was trying to maintain a whole page based RIC and was logging the partial updates for debugging purposes and noticed the above issue.

UPDATE:
Dumping the UpdateMsg before calling the apply() also messes up the RmtesBuffer apply operation so e.g. the following also results in the partial update replacing the existing buffer.

`	public void onUpdateMsg(UpdateMsg updateMsg, OmmConsumerEvent event) 
	{
		System.out.println(updateMsg);
		if (DataType.DataTypes.FIELD_LIST == updateMsg.payload().dataType())
			decode(updateMsg.payload().fieldList());
	
}`

**Comment by tmurthy** [comment]
Umer, 

There is an existing Jira ESDK-619 for this issue. We will update you when the Jira is fixed

Thanks
- Tina

**Comment by vlevendel** [comment]
@umernalla This has been address in ESDK1.3.0.L1.  Please let us know if there are further issues. Closing.
