### ISSUE TITLE
BufferOverflowException when calling permissionData() in EMA

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Elektron-SDK#77]
I have a client developer who has been developing an EMA Java application for past few months and been using version emaj3.1.0.E1 - which was the latest version at that time.
They have been doing UAT testing for a while with 1-2k instruments and all has been fine.
Today they increased the instrument list to 8k, for final testing in readiness for going into Production soon.
They have started seeing the following exception on random occasions (i.e. not linked to a particular instrument) when  they call RefreshMsg permissionData()

java.nio.BufferOverflowException: null
        at java.nio.Buffer.nextPutIndex(Buffer.java:521) ~[na:1.8.0_111]
        at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169) ~[na:1.8.0_111]
        at com.thomsonreuters.ema.access.Utilities.copyFromPool(Utilities.java:256) ~[ema-1.1.E1.jar:emaj3.1.0.E1.all.rrg]
        at com.thomsonreuters.ema.access.RefreshMsgImpl.permissionData(RefreshMsgImpl.java:132) ~[ema-1.1.E1.jar:emaj3.1.0.E1.all.rrg]

Is / was this a know issue? 

I don't see any mention on here or in the EMA README for v3.2 of permissionData() related exceptions.

They are reluctant to upgrade to v3.2 unless it has been definitely fixed in the release.

Thanks,

**Comment by JimCarroll64** [comment]
This does not appear to be a known issue. It is being investigated. We will contact you for additional information if necessary.

**Comment by vlevendel** [comment]
@umernalla Based on your communication with Premium support, closing this for now.  If there is further activity or if this is reproducible, please reopen.
