### ISSUE TITLE
OpenSSL version

### ISSUE THREAD

**Issue by linmaosong2018** [Refinitiv/Elektron-SDK#83]
Does the SDK need to be built against a particular OpenSSL version? With OpenSSL 1.1.0g, this error comes up

```
Elektron-SDK/Cpp-C/Eta/Impl/Transport/ripcssldh.c:82:7: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
     dh->p = (*(cryptoFuncs->bin2bn))(dh512_p, sizeof(dh512_p), NULL);
       ^~
Cpp-C/Eta/Impl/Codec/CMakeFiles/librssl_shared.dir/build.make:998: recipe for target 'Cpp-C/Eta/Impl/Codec/CMakeFiles/librssl_shared.dir/__/Transport/ripcssldh.c.o' failed
```

It appears to be [this issue](https://github.com/rakshasa/libtorrent/issues/138).

**Comment by MitchellKatoTR** [comment]
The current release was written to the 1.0.2 code line.  We are currently in the process of updating our openSSL usage, and 1.1.0 support will be added in a future release.

**Comment by linmaosong2018** [comment]
Thanks, @MitchellKatoTR , out of interest, does the Java SDK also have the same dependency?

**Comment by MitchellKatoTR** [comment]
Java uses the native Java SSLEngine libraries which are provided by the JVM, so there isn't an explicit dependency in the ESDK Java code.

**Comment by vlevendel** [comment]
This is been addressed with ESDK1.3.0. Please let us know if there are additional findings. Closing.
