### ISSUE TITLE
Elektron SDK v1.3 documentation regards ERT in Cloud connection and examples

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Elektron-SDK#98]
Hi all,
Great work on adding ERT in Cloud and Service discovery support to ESDK v1.3 - excellent stuff!

However, can we please urgently improve the README and other documentation for the ERT in Cloud related examples i.e. example113 and example450
Based on my experience, I believe many new developers would struggle to understand how to get the examples up and running in terms of the following:
1) which command line parameters to use (for example their ERT in Cloud Welcome email talks in terms of Machine ID (for the username) - what about all the other parameters - do I need them?
2) They may wonder if they need to use the proxy parameters or not for their particular situation.
3) The libcurl requirement - I can see mention of these in the Dev guide (under the HTTP Proxy section) and config guide (under RSSL_SOCKET parameters) . However, no mention in the README. Also the new user may notice that Channel_3 definition (as used by Consumer_3) in the provided EMAConfig.xml is defined as a ChannelType:RSSL_ENCRYPTED - so not obvious.
4) The EncryptedProtocolType parameter notes are confusing. It could be read as you have to use RSSL_HTTP for Windows - rather than RSSL_SOCKET ? I could not get it to connect with the default Windows value of RSSL_HTTP.
5) The Keystore file requirement - there is some mention about Keystore files under the Tunneling configuration section of the Dev Guide - but no clues or hints in the README file
 
I expect at some point an Article or some such document will be added to the developer portal - but there should be enough information / pointers in the README files that a new developer does not have to raise a ticket or post a query on the forum to merely get an example application up and running.

Thank you :)

**Comment by seba5** [comment]
Hi, 

we have updated the documentation with the latest github push, thank you for your feedback.
